language: python

services:
  - docker

#env:
#  global:
#  matrix:

before_install:
  - git clone --depth 1 https://github.com/NESII/esmf-travis-ci.git
  - cd esmf-travis-ci

script:
  - cd docker/esmf && docker build -t bekozi/esmf --build-arg ESMF_BRANCH=$TRAVIS_BRANCH .
  - cd docker/nuopc-protos && docker build -t bekozi/nuopc-protos .
